apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: to1-do1-app1
        image: trohan37/todoapp1:v1
        ports:
        - containerPort: 8000
